name: golangci-lint

on:
  push:
    branches:
      - feature/**

permissions:
  contents: read

jobs:
  iahfiehfuzefhe:
    runs-on: ubuntu-latest
    steps:
      - name: Update the Homebrew formula with latest release
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: Tchoupinax/check-git
          tap: Tchoupinax/homebrew-brew
          formula: ckg.rb
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
