name: tests

on:
  push:
    branches:
      - feature/**

jobs:
  perform-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.18.9, 1.19.4]
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Go vet check
        run: go vet ./...
      
      - name: Install ginkgo
        run: go get github.com/onsi/ginkgo/v2/ginkgo

      - name: Launch tests
        run: go run github.com/onsi/ginkgo/v2/ginkgo -r --randomize-all --randomize-suites --race --trace -cover
